In [1]:
import numpy as np

In [3]:
# 1. rand
rand_=np.random.rand(4,2)   #根据给定维度生成[0,1)之间的数据，包含0，不包含1
print(rand_)
print(np.shape(rand_))

[[0.68070469 0.04423485]
 [0.10637009 0.56671845]
 [0.00861201 0.36851297]
 [0.76688963 0.07725587]]
(4, 2)


In [5]:
# 2. randn
randn_=np.random.randn(4,2) #返回一个或一组样本，具有标准正态分布
print(randn_)

[[ 0.32351172  0.53433892]
 [-0.58246373  0.66134538]
 [-0.78636358  1.14217209]
 [-2.11122813 -0.19238754]]


In [6]:
# 3. randint
randint_=np.random.randint(1,5,(14,3)) #返回随机整数，范围区间为[low,high），包含low，不包含high
print((randint_))

[[2 2 4]
 [4 1 1]
 [2 4 3]
 [4 3 3]
 [1 4 4]
 [4 2 4]
 [1 3 2]
 [3 3 4]
 [3 3 2]
 [2 3 2]
 [2 2 2]
 [1 4 1]
 [2 1 3]
 [3 3 1]]


In [7]:
# 4. choice
arr=[1,3,5,7]
choice=np.random.choice(arr,(2,3)) #从给定的一维数组中生成随机数
print(choice)

[[1 7 3]
 [7 3 5]]


In [8]:
# 5. seed
np.random.seed(1)   #当我们设置相同的seed，每次生成的随机数相同。如果不设置seed，则每次会生成不同的随机数
print(np.random.rand())

0.417022004702574
